<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.YtjDpud' shared service.

return $this->privates['.service_locator.YtjDpud'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\MaterialController::additional_information' => ['privates', '.service_locator.eSzfOuO', 'get_ServiceLocator_ESzfOuOService.php', true],
    'App\\Controller\\MaterialController::index' => ['privates', '.service_locator.GBVqpY8', 'get_ServiceLocator_GBVqpY8Service.php', true],
    'App\\Controller\\MaterialController::update' => ['privates', '.service_locator.GBVqpY8', 'get_ServiceLocator_GBVqpY8Service.php', true],
    'App\\Controller\\MaterialController:additional_information' => ['privates', '.service_locator.eSzfOuO', 'get_ServiceLocator_ESzfOuOService.php', true],
    'App\\Controller\\MaterialController:index' => ['privates', '.service_locator.GBVqpY8', 'get_ServiceLocator_GBVqpY8Service.php', true],
    'App\\Controller\\MaterialController:update' => ['privates', '.service_locator.GBVqpY8', 'get_ServiceLocator_GBVqpY8Service.php', true],
], [
    'App\\Controller\\MaterialController::additional_information' => '?',
    'App\\Controller\\MaterialController::index' => '?',
    'App\\Controller\\MaterialController::update' => '?',
    'App\\Controller\\MaterialController:additional_information' => '?',
    'App\\Controller\\MaterialController:index' => '?',
    'App\\Controller\\MaterialController:update' => '?',
]);
