<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GBVqpY8' shared service.

return $this->privates['.service_locator.GBVqpY8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'repo' => ['privates', 'App\\Repository\\MaterialRepository', 'getMaterialRepositoryService.php', true],
], [
    'manager' => '?',
    'repo' => 'App\\Repository\\MaterialRepository',
]);
